[tool.basedpyright]
typeCheckingMode = "standard"
reportAny = false
reportUnknownVariableType = false
reportUnknownMemberType = false
reportOptionalMemberAccess = 'none'
reportOptionalSubscript = 'none'
reportOptionalCall = 'none'

[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = ["E", "W", "F", "I", "UP", "B", "SIM", "C4", "N", "RUF"]
ignore = ["F821", "F841"]
